# hugo.toml
baseURL = "https://kaka-notes.netlify.app/"
locale = "vi-VN"
title = "Kaka Notes"
pagination.pagerSize = 5

# Cấu hình Menu chính
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 3

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 4

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 5

[[menu.main]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"
  weight = 6

# Các tham số tùy chỉnh của theme (Params)
[params]
  abbrDateFmt = "Jan 02"
  author = "Trọng Nghĩa (Kaka)"
  brandIconFile = "images/brandIcon.svg"
  dateFmt = "2006-01-02"
  subtitle = "Ghi chép kiến thức, lập trình & công nghệ"

  # Mạng xã hội bên trong [params]
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/trongnghiango"

  [[params.social]]
    name = "GitLab"
    url = "https://gitlab.com/ntnghiatn"

  [[params.social]]
    name = "Reddit"
    url = "https://www.reddit.com/user/abc"

  [[params.social]]
    name = "StackOverflow"
    url = "https://stackoverflow.com/users/42949924/hsffhsj"

# Cấu hình xử lý Markdown và Cú pháp Code
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 2
